- name: SSH into remote server
  uses: appleboy/ssh-action@v1.0.0
  with:
    host: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    port: 22
    script: |
      cd public_html/api.networking.miami
      /opt/cpanel/ea-nodejs**/bin/npm install
      ./node_modules/typescript/bin/tsc
      /opt/cpanel/ea-nodejs**/bin/npm run build
      touch /home/networking/public_html/api.networking.miami/dist/tmp/restart.txt
