name: Publish Website to Cpanel
on:
  push:
    branches:
      - deploy

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Puedes ajustar la versión de Node.js según tus necesidades

      # Paso para desplegar el archivo
      - name: Deploy compressed files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: ./*
          remote_path: public_html/api.networking.miami

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Install dependencies
        run: npm run install
      



